# Generated by Django 2.2.17 on 2021-02-19 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_unlike', models.BooleanField(default=True)),
                ('liked_user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='liked_user', to=settings.AUTH_USER_MODEL)),
                ('tweet', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tweet', to='twitter.Tweet')),
            ],
        ),
    ]
